name: Node.js Package
# master push
on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.19.2] #指定node版本
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} #使用action安装node环境
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set Npm Info
      run: |
        npm config set registry https://registry.npmjs.org
        npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
        git config --global user.email "ah_wgs@126.com"
        git config --global user.name "ahwgs"

    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7.0.0

    - name: Support TLS1.2
      run: npm install -g https://tls-test.npmjs.com/tls-test-1.0.0.tgz

    - name: Install deps
      run: pnpm install

    - name: Build
      run: pnpm run build

    - name: Publish
      run: npm publish

